shopware:
    auto_update:
        # Disables the auto updater in the UI
#        enabled: false
    admin_worker:
        enable_admin_worker: true
        poll_interval: 30
        transports: ["default"]

    increment:
        user_activity:
            type: 'array'
        message_queue:
            type: 'array'
