# Yireo Shopware docker-compose 0.0.1
services:
  nginx:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sw6-pollux.rule=Host(`sw6.pollux.yr`)"
      - "traefik.http.routers.sw6-pollux.entrypoints=http"
    ports:
      - 80
    networks:
      - shopware
    volumes:
      - .:/var/www/html:rw
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - redis
      - php-fpm

  php-fpm:
    platform: linux/x86_64
    build: ./docker-compose/php-fpm
    ports:
      - 9000
    environment:
      - APP_URL=http://sw6-pollux/
      - INSTANCE_ID=
      - SHOPWARE_ES_ENABLED=1
      - SHOPWARE_ES_HOSTS=elasticsearch:9200
      - SHOPWARE_ES_INDEXING_ENABLED=1
      - SHOPWARE_ES_INDEX_PREFIX=sw
      - SHOPWARE_CDN_STRATEGY_DEFAULT=id
      - MAILER_URL=smtp://localhost:25?encryption=&auth_mode=
    networks:
      - shopware
    volumes:
      - .:/var/www/html:rw
      - /data/git:/data/git
      - /usr/local/bin/symfony:/usr/local/bin/symfony
      - ~/.composer:/var/www/.composer
    depends_on:
      - mysql
      - elasticsearch
      - redis

  mysql:
    image: mysql:8.0
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql-pollux.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql-pollux.entrypoints=mysql"
    ports:
      - 3306
    networks:
      - shopware
    volumes:
      - ./docker-compose/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopware6
      - MYSQL_USER=shopware6
      - MYSQL_PASSWORD=shopware6
    tmpfs:
      - /tmp

  elasticsearch:
    image: elasticsearch:7.17.5
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.elasticsearch-pollux.rule=Host(`*`)"
      - "traefik.tcp.routers.elasticsearch-pollux.entrypoints=elasticsearch"
      - "traefik.tcp.routers.mysql.service=elasticsearch"
    ports:
      - 9200
    networks:
      - shopware
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    tmpfs:
      - /tmp

  redis:
    image: redis:7.0
    ports:
      - 6379
    networks:
      - shopware

  varnish:
    image: varnish:stable
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.varnish-pollux.rule=Host(`varnish.pollux.yr`)"
      - "traefik.http.routers.varnish-pollux.tls=true"
      - "traefik.http.routers.varnish-pollux.entrypoints=http"
      #volumes:
      #- ./default.vcl:/etc/varnish/default.vcl
    ports:
      - 80
    networks:
      - shopware
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    depends_on:
      - nginx

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672
      - 15672
    networks:
      - shopware

networks:
    shopware:
        driver: bridge

volumes:
    mysqldata:
    esdata:
