# Yireo Shopware docker-compose 0.0.1
services:
  nginx:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sw6-pollux.rule=Host(`sw6.pollux.yr`)"
      - "traefik.http.routers.sw6-pollux.entrypoints=http"
      - "traefik.http.routers.sw6-pollux.service=sw6-pollux"
      - "traefik.http.services.sw6-pollux.loadbalancer.server.port=80"
    ports:
      - 80
    networks:
      - shopware
    volumes:
      - .:/var/www/html:rw
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - redis
      - php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-fpm:
    platform: linux/x86_64
    build: ./docker-compose/php-fpm
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.sw6webpack-pollux.rule=Host(`sw6.pollux.yr`)"
      - "traefik.http.routers.sw6webpack-pollux.entrypoints=sw6webpack"
      - "traefik.http.routers.sw6webpack-pollux.service=sw6webpack"
      - "traefik.http.services.sw6webpack.loadbalancer.server.port=9998"

      - "traefik.http.routers.sw6livereload-pollux.rule=Host(`sw6.pollux.yr`)"
      - "traefik.http.routers.sw6livereload-pollux.entrypoints=sw6livereload"
      - "traefik.http.routers.sw6livereload-pollux.service=sw6livereload"
      - "traefik.http.services.sw6livereload.loadbalancer.server.port=9999"
    ports:
      - 9000
      - 9998
      - 9999
    environment:
      - APP_URL=http://sw6-pollux/
      - INSTANCE_ID=
      - SHOPWARE_ES_ENABLED=1
      - SHOPWARE_ES_HOSTS=elasticsearch:9200
      - SHOPWARE_ES_INDEXING_ENABLED=1
      - SHOPWARE_ES_INDEX_PREFIX=sw
      - SHOPWARE_CDN_STRATEGY_DEFAULT=id
      - MAILER_URL=smtp://localhost:25?encryption=&auth_mode=
    networks:
      - shopware
    volumes:
      - .:/var/www/html:rw
      - /data/git:/data/git
      - ~/.composer:/var/www/.composer
    depends_on:
      - mysql
      - elasticsearch
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql-pollux.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql-pollux.entrypoints=mysql"
    ports:
      - 3306
    networks:
      - shopware
    volumes:
      - ./docker-compose/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopware6
      - MYSQL_USER=shopware6
      - MYSQL_PASSWORD=shopware6
    tmpfs:
      - /tmp

  elasticsearch:
    #image: elasticsearch:7.17.5
    image: opensearchproject/opensearch:2
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.elasticsearch-pollux.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.elasticsearch-pollux.entrypoints=elasticsearch"
    ports:
      - 9200
    networks:
      - shopware
    environment:
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -Xss1m"
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - discovery.type=single-node
      - plugins.security.disabled=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - script.painless.regex.enabled=true
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - plugins.security.ssl.http.enabled=false
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    tmpfs:
      - /tmp

  redis:
    image: redis:7.0
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis-pollux.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.redis-pollux.entrypoints=redis"
    ports:
      - 6379
    networks:
      - shopware

  varnish:
    image: varnish:stable
    labels:
      #- "traefik.enable=true"
      - "traefik.http.routers.varnish-pollux.rule=Host(`varnish.pollux.yr`)"
      - "traefik.http.routers.varnish-pollux.entrypoints=http"
      - "traefik.http.routers.varnish-pollux.tls=true"
    #volumes:
    #  - ./default.vcl:/etc/varnish/default.vcl
    ports:
      - 80
    networks:
      - shopware
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    depends_on:
      - nginx

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672
      - 15672
    networks:
      - shopware

networks:
    shopware:
        driver: bridge

volumes:
    mysqldata:
    esdata:
